### ISSUE TITLE
gpitv: improved display for polarization slice images

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#10]
For polarization slice pairs, the datacube display menu should have an option to difference the two slices. 
Also the polarization label text should be updated or debugged to properly display what each slice is.  (including perhaps taking the WPangle into consideration?)

**Comment by dsavransky** [comment]
Recovering rm journals for issue:

mperrin: Difference of two polarization slices does exist. 
Labeling could be improved, maybe?

**Comment by mperrin** [comment]
Legacy issue migrated from redmine issue tracker. Originally filed by @mperrin on 2012-04-09

I'm going to close this now because there is little/no use case for looking at orthogonal polarization pairs in gpitv at this point. I don't see any compelling reason to improve that. @maxwellmb I presume you agree?
