### ISSUE TITLE
deep wavecal recipe fails on looking up DQ frame

### ISSUE THREAD

**Issue by semaphoreP** [geminiplanetimager/gpi_pipeline#100]
Trying to process the latest wavecals taken this month using the Data Cruncher/Data Parser, I've run into the following error: 

![image](https://cloud.githubusercontent.com/assets/2245740/18483582/797099d6-7999-11e6-931f-9385813ef64d.png)

On closer inspection, the appropriate line of code is the following line (the one that isn't a comment):
    ;READ IN BAD PIXEL MAP
    ; assume this is already present in the DQ extension.
    badpix=*dataset.currdq GT 0

Have there been recent changes to how the DQ frame works? Have anyone else hit this issue?

Here's the recipe to reproduce the bug:
<?xml version="1.0" encoding="UTF-8"?>
<recipe Name="Wavelength Solution 2D Developer" ReductionType="Calibration" ShortName="wavecal2">

<dataset InputDir="/home/public/Dropbox/GPIDATA-Readonly/Campaign/Raw/160911" OutputDir="/home/public/Dropbox/GPIDATA-Calibrations/Data_Cruncher/2016A/">
   <fits FileName="S20160911S0613.fits.gz" />
   <fits FileName="S20160911S0614.fits.gz" />
   <fits FileName="S20160911S0615.fits.gz" />
   <fits FileName="S20160911S0616.fits.gz" />
   <fits FileName="S20160911S0617.fits.gz" />
</dataset>
<primitive name="Apply Reference Pixel Correction" Save="           0" gpitv="0" smoothing_size="31" before_and_after="0" Method="INTERPOLATED" />
<primitive name="Add DISPERSR keyword if missing" value="DISP_PRISM_G6262" />
<primitive name="Subtract Dark Background" CalibrationFile="AUTOMATIC" RequireExactMatch="0" Interpolate="0" Save="           0" gpitv="0" />
<primitive name="Subtract Thermal/Sky Background if K band" CalibrationFile="AUTOMATIC" Save="           0" Override_scaling="1.0" gpitv="10" />
<primitive name="Interpolate bad pixels in 2D frame" CalibrationFile="AUTOMATIC" method="vertical" Save="           0" gpitv="0" negative_bad_thresh="-50" before_and_after="0" usedq="0" />
<primitive name="Quick Wavelength Solution Update" Display="-1" spacing="20" boxsizex="7" boxsizey="24" xoffset="0" yoffset="0" whichpsf="0" higher_order_correction="1" CalibrationFile="AUTOMATIC" Save="1" AutoOffset="1" gpitvim_dispgrid="10" />
<primitive name="Quality Check Wavelength Calibration" error_action="Fail" Display="-1" Save="1" />
<primitive name="Accumulate Images" Method="InMemory" />
<primitive name="2D Wavelength Solution Developer" display="0" whichpsf="1" parallel="1" numsplit="0" Save="1" Smooth="1" Save_model_image="1" CalibrationFile="AUTOMATIC" Save_model_params="1" AutoOffset="0" />
<primitive name="Quality Check Wavelength Calibration" error_action="Ask_user" Display="-1" Save="0" />
</recipe>

**Comment by mperrin** [comment]
attention @swolff9 @kfollette

**Comment by mperrin** [comment]
@semaphoreP the recipe you pasted didn't seem to show up cleanly here in github

**Comment by semaphoreP** [comment]
Whoops, here's the recipe file as a text file:

[wavecal_dq_fail.txt](https://github.com/geminiplanetimager/gpi_pipeline/files/470381/wavecal_dq_fail.txt)

**Comment by swolff9** [comment]
OK, so I've traced the problem, but it doesn't have an obvious solution. At the end of the quick wavecal primitive, the current frame is set to the shifted wavecal so that the new wavecal can be written. The DQ extensions are also reset at this point:
*dataset.currframe = shiftedwavecal
ptr_free, dataset.currDQ, dataset.currUncert

When we go to reduce the full wavelength solution, it doesn't get the raw files it was expecting, and the thing fails. It actually fails first when trying to call the DQ extension, but it will still fail even if we don't clear the data quality extension in the quick wavecal primitive because the current frame is incorrect. 

The goal of adding the quick wavelength solution primitive to the developer code was to handle the all too common case where there is a 3 pixel shift from one deep wavecal sequence to another. The fit will fail because the boxes to extract the spectra for fitting are drawn in the wrong place. Generally I fix this manually by running the quick wavelength solution on the data which is more robust to 3 pixel shifts, but less accurate. 

It seems the obvious solution would be to just run two recipes on all wavecal files. First the quick, then the full developer version. However, unless I am mistaken the data parser logic only allows one recipe template name to be returned. Am I mistaken in this? Anyone see a better solution?

**Comment by swolff9** [comment]
For now I've pushed a change to the recipe template to remove the quick wavecal portion.

**Comment by mperrin** [comment]
Actually it turns out that we did work out a way for the data parser to make more than one recipe using different templates on the same data set. Take a look at how the pol calibrations are created in parsercore. Instead of trying to pass back multiple template names we just create the several recipes right away inside the case statement. So you can definitely set it up with two recipes for the wavecal reductions. Thanks for figuring this out.

**Comment by swolff9** [comment]
Great, I've made the changes and am running a test now. It looks like I've generated the recipes in the correct order, so that the quick wavecals will be generated before the deep ones. If all goes well, I will push the changes to the repository in a few minutes. Jason: will you have a chance to test this on the Data Cruncher before the run, or should I generate the wavecals?

**Comment by swolff9** [comment]
OK, changes pushed

**Comment by semaphoreP** [comment]
Cool! I can run them through the data cruncher later today and check them tomorrow. Thanks for figure it out!

**Comment by semaphoreP** [comment]
H band deep wavecals were successful so I think the workaround should be fine. Closing the issue now!

**Comment by swolff9** [comment]
thanks
