### ISSUE TITLE
testing data not where I expected it to be on Dropbox

### ISSUE THREAD

**Issue by semaphoreP** [geminiplanetimager/gpi_pipeline#102]
For me, the pipeline_testing_dataset folder is in the Dropbox folder "Pipeline_Releases (1)" instead of "Pipeline_Releases" as "Pipeline_Releases" seems to be an obsolete and empty folder on Dropbox. Is this just an issue for me? It seems like @mperrin also has access to this old folder.

**Comment by mperrin** [comment]
At some point during one of the dropbox reorgs, the Pipeline_Releases folder got messed up. I ended up with a duplicate copy marked Selective Sync Conflict or something like that, which I had to get rid of, in order to have the folder sync to the right name. 

My suggestion is to check your selective sync settings, turn off sync for the shared folder, delete your obsolete empty local folder, then re-enable sync of the shared folder which should hopefully give you one without the "(1)"

**Comment by semaphoreP** [comment]
Deleting the extra folder and then renaming the Dropbox folder back to "Pipeline_Releases" worked as you advised on Slack. Closing this issue now.
